name: Test and release

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pre-commit
          pip install .

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: thirsty examples/test.gpx output.gpx

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # <<< only run bump if push to main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          pip install .

      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cz bump --yes
          git push origin HEAD:main
          git push --tags
