name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pre-commit
          pip install .

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: thirsty examples/test.gpx output.gpx
